# This will set the language of the plugin.
# You will find different language files inside \languages\.
# Write their file name (without *.yml) down below to use the respective language.
language: en_US