name: MobileCrafting
description: ${project.description}
author: ItsLeMax
version: ${project.version}
website: ${project.url}

main: de.max.mobilecrafting.init.MobileCrafting
api-version: 1.20
commands:
  mobilecraft:
    description: /give equivalent for the crafter item
    usage: /mobilecraft