name: MobileCrafting
description: ${project.description}
author: ItsLeMax
version: ${project.version}
website: ${project.url}

depend: [ ILMLib ]
main: de.fpm_studio.mobilecrafting.MobileCrafting
api-version: 1.20
commands:
  givemobilecrafter:
    description: /give equivalent for the crafter item
    usage: /givemobilecrafter